### ISSUE TITLE
Array bug | rewrite failed, key does not exist

### ISSUE THREAD

**Issue by t1k3** [larapack/config-writer#14]
Example 1: 
```
app.php > 'locales' => ['en'],
$locales = ['en-GB'];
Config::write('app', ['locales' => $locales]);
```
Exception in Repository.php line 146:
Unable to rewrite key "locales.0" in config, rewrite failed

Example 2: 
```
app.php > 'locales' => ['en'],
$locales = ['en', 'en-GB'];
Config::write('app', ['locales' => $locales]);
```
Exception in Repository.php line 137:
Unable to rewrite key "locales.1" in config, does it exist?

**Comment by marktopper** [comment]
Duplicate of #11
