### ISSUE TITLE
Error while writing to File

### ISSUE THREAD

**Issue by mchampaneri** [larapack/config-writer#5]
ensurePathsExists($to); 

function not working well in the windows based system

**Comment by marktopper** [comment]
If I'm not right, Windows uses another directory separator.

I have made some changes which hopefully should do the fix, can you please try the newest master and report back.

**Comment by mchampaneri** [comment]
Not working same problem

**Comment by marktopper** [comment]
Do you get any error message?

**Comment by mchampaneri** [comment]
ErrorException in Filesystem.php line 387:
mkdir(): Invalid argument

**Comment by mchampaneri** [comment]
28.		$this->ensurePathsExists($to);

Remove this if it is not  needed. Because  after commenting it , it works fine

**Comment by marktopper** [comment]
Thanks.

I will boot up a Windows machine and check it out, will update this issue when done.

**Comment by marktopper** [comment]
`mkdir` normally only come out with this error when there are special characters in the path.

What is the code that you are trying to run?

**Comment by mchampaneri** [comment]
/*** config  file to be written  site.php***/

return [
    'site_name' => 'Your Site Name',
    'twitter_url' => '',
    'google_plus_url' => '',
    'facebook_url' => 'your facebook.com',
    ];

/***  route used to write the file  ***/  
Route::post('/setsiteprofile',function() {
        $input = Request::all();
        Config::write('site',['site_name'=>$input['site_name'],
            'twitter_url'=>$input['twitter_url'],
            'facebook_url'=>$input['facebook_url'],
            'google_plus_url'=>$input['google_plus_url']
        ]);

/*** Path of file used windows system ***/
D:\SERVER\laragon\www\untitled1\config\site.php

**Comment by weidmaster** [comment]
@marktopper Same issue here. Commenting the line that @mchampaneri pointed out do work. Please check the method again. I am testing in a Windows 7 machine with XAMPP.

I think the following output shows the problem. The code is actually adding some slashes to the Windows path style:

1.  in Filesystem.php line 387
2. at HandleExceptions->handleError('2', 'mkdir(): Invalid argument', 'C:\xampp\htdocs\ens\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php', '387', array('path' => '/C:\xampp\htdocs\ens\config/', 'mode' => '493', 'recursive' => false, 'force' => false))
3. at mkdir('/C:\xampp\htdocs\ens\config/', '493', false) in Filesystem.php line 387
4. at Filesystem->makeDirectory('/C:\xampp\htdocs\ens\config/') in Repository.php line 60
5. at Repository->ensurePathsExists('C:\xampp\htdocs\ens\config/sis.php') in Repository.php line 29

**Comment by marktopper** [comment]
I see @weidmaster, thanks for the stack-trace.

Will hopefully have a fix up later today.

**Comment by marktopper** [comment]
This have been fixed in v1.0.1 🎉
